### ISSUE TITLE
USB Type A socket

### ISSUE THREAD

**Issue by borb** [borb/amigahid-pico#7]
Add a USB type A socket. This can be done by either:

* connecting to the micro-USB port and providing a type A socket; hacky but stable
* attaching to test points beneath the micro-USB socket and running to a type A socket

**Comment by borb** [comment]
Added in revision 4 (see 65ffd97fab697f31d4ec6cc0d69d6c9d1e991e65). Awaiting PCB delivery to test.

**Comment by borb** [comment]
Protos arrived today. Didn't specify castellated edges, but the finish is easily acceptable (the aperture is super tiny though, so this is either a hot air or tiny tip job. Had to trim some hanging via plating with a scalpel. Test pads line up ok, solder mask looks suitable. Think this might work ok.

Will assemble tomorrow.

**Comment by borb** [comment]
Ok, it works.

![image](https://user-images.githubusercontent.com/7986200/164497921-42eb7bf3-7aae-422c-b9e3-aa68c2d092a1.png)

I'm keeping it external whilst I probe around the pins to see what's firing where, but everything works. Still need to move the ground plane via, which is in the Pico's keepout area. But success.

**Comment by rfuest** [comment]
Nice, the USB A connector looks so much better than an OTG adapter. I think I should build one.

**Comment by borb** [comment]
> Nice, the USB A connector looks so much better than an OTG adapter. I think I should build one.

I have more boards than I am going to use in this production run. Would you like a couple of samples sent to you?

**Comment by rfuest** [comment]
Thanks for the offer. I'm not sure where you are located, but unfortunately it's often cheaper to order new PCBs for China than paying postage for PCBs.

**Comment by borb** [comment]
Socket is working. Closing.
